services:
  # soanr 服务
  sonarqube:
    image: sonarqube:10.7.0-community
    container_name: sonarqube
    restart: always
    depends_on:
      - sonar-db
    ports:
      - '39000:9000'
    networks:
      - sonar-net
    deploy:
      resources:
        limits:
          cpus: '6'
          memory: 16G
        reservations:
          memory: 2G
    environment:
      - TZ=Asia/Shanghai
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonar-db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - './conf/sonar.properties:/opt/sonarqube/conf/sonar.properties'
      - '/mnt/sonarqube/data:/opt/sonarqube/data'
      - '/mnt/sonarqube/logs:/opt/sonarqube/logs'
      - '/mnt/sonarqube/extensions:/opt/sonarqube/extensions'
      - '/mnt/sonarqube/lib/bundled-plugins-plugins:/opt/sonarqube/lib/bundled-plugins'
      - '/opt/sonarqube/plugins:/opt/sonarqube/extensions/plugins'
  # sonar db
  sonar-db:
    image: postgres:15.4
    container_name: sonar-db
    restart: always
    networks:
      - sonar-net
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8G
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - '/mnt/sonarqube/postgresql:/var/lib/postgresql'
      - '/mnt/sonarqube/postgresql/data/:/var/lib/postgresql/data'
# network config
networks:
  sonar-net:
    driver: bridge