#MDS UI
server {
    listen          9001;
    index           index.html;
    gzip on;
    gzip_vary on;
    gzip_min_length 1000;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_buffers 16 8k;
    gzip_http_version 1.1;

    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript application/x-font-ttf font/opentype image/svg+xml image/x-icon;
    underscores_in_headers on;

    location ~* .*\.(js|css|ico|png|jpg|eot|svg|ttf|woff|woff2|html|json|gif|swf) {
        root /opt/mes/mds/mycim-mds-ui;
    }

    location = / {
        root   /opt/mes/mds/mycim-mds-ui;
        index  index.html;
    }

    location = /index.html {
        root   /opt/mes/mds/mycim-mds-ui;
        add_header Cache-Control 'no-cache, no-store, max-age=0, must-revalidate';
    }

    location /mds {
        rewrite ^/mds/(.*)$ /$1 break;
        proxy_pass http://192.168.10.210:9000;#可调整
        # proxy_redirect off;
        proxy_set_header MCLASS_ID $http_mclass_id;
        proxy_set_header MTRANSACTION_ID $http_mtransaction_id;
        proxy_set_header MVERSION $http_mversion;
        proxy_set_header MTOKEN $http_mtoken;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header REMOTE-HOST $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto  $scheme;
        proxy_set_header Host $http_host;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        client_max_body_size 100m;
        client_body_buffer_size 512k;
        proxy_connect_timeout 90;
        proxy_send_timeout 1200;
        proxy_read_timeout 1200;
        proxy_buffer_size 64k;
        proxy_buffers 4 128k;
        proxy_busy_buffers_size 256k;
        proxy_temp_file_write_size 256k;
    }
}
