# GitLab Server
services:
  # gitlab 服务
  gitlab:
    image: gitlab/gitlab-ce:17.4.3-ce.0
    container_name: gitlab-ce
    restart: always
    environment:
      TZ: 'Asia/Shanghai'
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://10.10.50.200:30080'
        gitlab_rails['gitlab_shell_ssh_port'] = 22
    privileged: true
    shm_size: '16gb'
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 24G
        reservations:
          memory: 6G
    ports:
      - '30080:30080'
      - '30022:22'
      - '30443:443'
    volumes:
      - '/mnt/gitlab/config:/etc/gitlab'
      - '/mnt/gitlab/logs:/var/log/gitlab'
      - '/mnt/gitlab/data:/var/opt/gitlab'
    