server {
    listen       20601;
    server_name  localhost;

    #charset koi8-r;

    #access_log  logs/host.access.log  main;

    location ~ .*\.(js|css|ico|png|jpg|eot|svg|ttf|woff|html|json|gif|swf|xlsx|xls) {
        root /opt/mes/uac/mycim-uac-ui-new;
        add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
    }
    location = / {
        index  /index.html;
        add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
        #try_files $uri $uri/ /index.html =404;
    }

    location / {
        proxy_pass http://192.168.10.210:20600;
        proxy_redirect off;
        proxy_set_header Host $host:8202;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header REMOTE-HOST $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
        proxy_set_header X-Forwarded-Proto  $scheme;
        client_max_body_size 100m;
        client_body_buffer_size 128k;
        proxy_connect_timeout 90;
        proxy_send_timeout 90;
        proxy_read_timeout 90;
        proxy_buffer_size 4k;
        proxy_buffers 4 32k;
        proxy_busy_buffers_size 64k;
        proxy_temp_file_write_size 64k;
    }
}
