# 此配置文件由官方脚本生成，然后进行改造的
# 参考：https://juejin.cn/post/7223027325037789241
# 镜像存储使用 MinIO，参考：https://doc.itopcms.com/docs/sys_arch/sys_arch-1fk1ld9rkl3re
services:
  log:
    image: goharbor/harbor-log:v2.12.0
    container_name: harbor-log
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8G
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
    volumes:
      - /var/log/harbor/:/var/log/docker/:z
      - type: bind
        source: ./common/config/log/logrotate.conf
        target: /etc/logrotate.d/logrotate.conf
      - type: bind
        source: ./common/config/log/rsyslog_docker.conf
        target: /etc/rsyslog.d/rsyslog_docker.conf
    ports:
      - 127.0.0.1:30514:10514
    networks:
      - harbor
  registry:
    image: goharbor/registry-photon:v2.12.0
    container_name: harbor-registry
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8G
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    volumes:
      - /data/registry:/storage:z
      - ./common/config/registry/:/etc/registry/:z
      - type: bind
        source: /data/secret/registry/root.crt
        target: /etc/registry/root.crt
      - type: bind
        source: ./common/config/shared/trust-certificates
        target: /harbor_cust_cert
    networks:
      - harbor
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://localhost:30514"
        tag: "registry"
  registryctl:
    image: goharbor/harbor-registryctl:v2.12.0
    container_name: harbor-registryctl
    env_file:
      - ./common/config/registryctl/env
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8G
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    volumes:
      - /data/registry:/storage:z
      - ./common/config/registry/:/etc/registry/:z
      - type: bind
        source: ./common/config/registryctl/config.yml
        target: /etc/registryctl/config.yml
      - type: bind
        source: ./common/config/shared/trust-certificates
        target: /harbor_cust_cert
    networks:
      - harbor
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://localhost:30514"
        tag: "registryctl"
  postgresql:
    image: goharbor/harbor-db:v2.12.0
    container_name: harbor-db
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8G
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
    volumes:
      - /data/database:/var/lib/postgresql/data:z
    networks:
      harbor:
    env_file:
      - ./common/config/db/env
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://localhost:30514"
        tag: "postgresql"
    shm_size: '1gb'
  core:
    image: goharbor/harbor-core:v2.12.0
    container_name: harbor-core
    env_file:
      - ./common/config/core/env
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 16G
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
    volumes:
      - /data/ca_download/:/etc/core/ca/:z
      - /data/:/data/:z
      - ./common/config/core/certificates/:/etc/core/certificates/:z
      - type: bind
        source: ./common/config/core/app.conf
        target: /etc/core/app.conf
      - type: bind
        source: /data/secret/core/private_key.pem
        target: /etc/core/private_key.pem
      - type: bind
        source: /data/secret/keys/secretkey
        target: /etc/core/key
      - type: bind
        source: ./common/config/shared/trust-certificates
        target: /harbor_cust_cert
    networks:
      harbor:
    depends_on:
      - log
      - registry
      - redis
      - postgresql
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://localhost:30514"
        tag: "core"
  portal:
    image: goharbor/harbor-portal:v2.12.0
    container_name: harbor-portal
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 16G
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - NET_BIND_SERVICE
    volumes:
      - type: bind
        source: ./common/config/portal/nginx.conf
        target: /etc/nginx/nginx.conf
    networks:
      - harbor
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://localhost:30514"
        tag: "portal"

  jobservice:
    image: goharbor/harbor-jobservice:v2.12.0
    container_name: harbor-jobservice
    env_file:
      - ./common/config/jobservice/env
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8G
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    volumes:
      - /data/job_logs:/var/log/jobs:z
      - type: bind
        source: ./common/config/jobservice/config.yml
        target: /etc/jobservice/config.yml
      - type: bind
        source: ./common/config/shared/trust-certificates
        target: /harbor_cust_cert
    networks:
      - harbor
    depends_on:
      - core
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://localhost:30514"
        tag: "jobservice"
  redis:
    image: goharbor/redis-photon:v2.12.0
    container_name: harbor-redis
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8G
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    volumes:
      - /data/redis:/var/lib/redis
    networks:
      harbor:
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://localhost:30514"
        tag: "redis"
  proxy:
    image: goharbor/nginx-photon:v2.12.0
    container_name: harbor-nginx
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8G
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - NET_BIND_SERVICE
    volumes:
      - ./common/config/nginx:/etc/nginx:z
      - type: bind
        source: ./common/config/shared/trust-certificates
        target: /harbor_cust_cert
    networks:
      - harbor
    ports:
      - 38080:8080
      - 39090:9090
    depends_on:
      - registry
      - core
      - portal
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://localhost:30514"
        tag: "proxy"
  exporter:
    image: goharbor/harbor-exporter:v2.12.0
    container_name: harbor-exporter
    env_file:
      - ./common/config/exporter/env
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8G
    networks:
      - harbor
    depends_on:
      - core
      - postgresql
    volumes:
      - type: bind
        source: ./common/config/shared/trust-certificates
        target: /harbor_cust_cert
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://localhost:30514"
        tag: "exporter"

networks:
  harbor:
    external: false
