version: "3.9"

services:
  # jenkins
  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins
    ports:
      - 8088:8080
      - 50000:50000
    volumes:
      - ./data/:/var/jenkins_home/