services:
  minio:
    image: minio/minio:RELEASE.2024-11-07T00-52-20Z
    container_name: minio
    ports:
      - '29000:9000'
      - '29001:9001'
    restart: always
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
    volumes:
      - /mnt/minio/data:/data
    #指定容器中的目录 /data
    command: server --console-address ':9001' /data
    privileged: true
    deploy:
      resources:
        limits:
          cpus: '6'
          memory: 24G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3