input {
  beats {
    port => 5044
    host => "0.0.0.0"
  }
}

filter {
  grok {
    match => {
      "message" => "%{TIMESTAMP_ISO8601:time} \[%{DATA:appName},%{DATA:traceId},%{DATA:spanId},%{DATA:traceFlags}\] \[%{DATA:threadId}\] %{LOGLEVEL:log.level}  %{DATA:methods} \- %{GREEDYDATA:log.message}"
    }
  }
}

output {
  elasticsearch {
    # es地址
    hosts => "http://es:9200"
    # index name
    index => "log_eric_%{[fields][app_name]}_%{[fields][env]}_%{+YYYY-MM-dd}"
  }
}
