services:
  # db service for zentao
  zentao-db:
    image: mariadb:10.6
    container_name: zentao-db
    restart: always
    ports:
      - '33306:3306'
    volumes:
      - /mnt/zentao/mysql:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=fapass4Zentao
      - MYSQL_DATABASE=zentao
    networks:
      - zentao-net

  # zentao service
  zentao:
    image: easysoft/zentao:18.7
    container_name: zentao
    restart: always
    ports:
      - '30081:80'
    volumes:
      - /mnt/zentao/data:/data
      - /mnt/zentao/module:/module
      - /mnt/zentao/config:/config
      - /mnt/zentao/db:/db
    depends_on:
      - zentao-db
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G
        reservations:
          memory: 2G
    environment:
      - TZ=Asia/Shanghai
      - ZT_MYSQL_HOST=zentao-db
      - ZT_MYSQL_PORT=3306
      - ZT_MYSQL_USER=root
      - ZT_MYSQL_PASSWORD=fapass4Zentao
      - ZT_MYSQL_DB=zentao
      - PHP_MAX_EXECUTION_TIME=120
      - PHP_MEMORY_LIMIT=512M
      - PHP_POST_MAX_SIZE=128M
      - PHP_UPLOAD_MAX_FILESIZE=128M
      - LDAP_ENABLED=true
      - SMTP_ENABLED=true
      - APP_DEFAULT_PORT=80
      - APP_DOMAIN=zentao.pdc.fa.com
      - PROTOCOL_TYPE=http
      - IS_CONTAINER=true
      - LINK_GIT=false
      - LINK_CI=false
    mac_address: 02:42:ac:11:00:ff
    networks:
      - zentao-net

networks:
  zentao-net:
    driver: bridge